graph TD;
    abstra_internals/contract/__init__.py --> abstra_internals/contract/__init__.py;
    abstra_internals/controllers/sdk_ai.py --> abstra_internals/widgets/response_types.py;
    abstra_internals/widgets/response_types.py --> abstra_internals/widgets/file_utils.py;
    abstra_internals/widgets/file_utils.py --> abstra_internals/controllers/sdk_context.py;
    abstra_internals/controllers/sdk_context.py --> abstra_internals/controllers/sdk_ai.py;
    abstra_internals/email_templates/__init__.py --> abstra_internals/email_templates/__init__.py;
    abstra_internals/email_templates/__init__.py --> abstra_internals/email_templates/authentication.py;
    abstra_internals/email_templates/authentication.py --> abstra_internals/email_templates/__init__.py;
    abstra_internals/email_templates/__init__.py --> abstra_internals/email_templates/message.py;
    abstra_internals/email_templates/message.py --> abstra_internals/email_templates/__init__.py;
    abstra_internals/email_templates/__init__.py --> abstra_internals/email_templates/task_waiting.py;
    abstra_internals/email_templates/task_waiting.py --> abstra_internals/email_templates/__init__.py;
    abstra_internals/interface/sdk/connectors/__init__.py --> abstra_internals/interface/sdk/connectors/__init__.py;
    abstra_internals/interface/sdk/forms/generated/widget_schema.py --> abstra_internals/interface/sdk/forms/reactive.py;
    abstra_internals/interface/sdk/forms/reactive.py --> abstra_internals/interface/sdk/forms/page.py;
    abstra_internals/interface/sdk/forms/page.py --> abstra_internals/interface/sdk/forms/generated/widget_schema.py;
    abstra_internals/interface/sdk/forms/page.py --> abstra_internals/interface/sdk/forms/reactive.py;
    abstra_internals/interface/sdk/forms/reactive.py --> abstra_internals/interface/sdk/forms/page.py;
    abstra_internals/linter/rules/__init__.py --> abstra_internals/linter/rules/__init__.py;
    abstra_internals/logger.py --> abstra_internals/utils/__init__.py;
    abstra_internals/utils/__init__.py --> abstra_internals/utils/packages.py;
    abstra_internals/utils/packages.py --> abstra_internals/logger.py;
    abstra_internals/repositories/project/json_migrations/__init__.py --> abstra_internals/repositories/project/json_migrations/__init__.py;
    abstra_internals/repositories/project/json_migrations/__init__.py --> abstra_internals/repositories/project/json_migrations/migration_001.py;
    abstra_internals/repositories/project/json_migrations/migration_001.py --> abstra_internals/repositories/project/json_migrations/__init__.py;
    abstra_internals/repositories/project/json_migrations/__init__.py --> abstra_internals/repositories/project/json_migrations/migration_002.py;
    abstra_internals/repositories/project/json_migrations/migration_002.py --> abstra_internals/repositories/project/json_migrations/__init__.py;
    abstra_internals/repositories/project/json_migrations/__init__.py --> abstra_internals/repositories/project/json_migrations/migration_003.py;
    abstra_internals/repositories/project/json_migrations/migration_003.py --> abstra_internals/repositories/project/json_migrations/__init__.py;
    abstra_internals/repositories/project/json_migrations/__init__.py --> abstra_internals/repositories/project/json_migrations/migration_004.py;
    abstra_internals/repositories/project/json_migrations/migration_004.py --> abstra_internals/repositories/project/json_migrations/__init__.py;
    abstra_internals/repositories/project/json_migrations/__init__.py --> abstra_internals/repositories/project/json_migrations/migration_005.py;
    abstra_internals/repositories/project/json_migrations/migration_005.py --> abstra_internals/repositories/project/json_migrations/__init__.py;
    abstra_internals/repositories/project/json_migrations/__init__.py --> abstra_internals/repositories/project/json_migrations/migration_006.py;
    abstra_internals/repositories/project/json_migrations/migration_006.py --> abstra_internals/repositories/project/json_migrations/__init__.py;
    abstra_internals/repositories/project/json_migrations/__init__.py --> abstra_internals/repositories/project/json_migrations/migration_007.py;
    abstra_internals/repositories/project/json_migrations/migration_007.py --> abstra_internals/repositories/project/json_migrations/__init__.py;
    abstra_internals/repositories/project/json_migrations/__init__.py --> abstra_internals/repositories/project/json_migrations/migration_009.py;
    abstra_internals/repositories/project/json_migrations/migration_009.py --> abstra_internals/repositories/project/json_migrations/__init__.py;
    abstra_internals/repositories/project/json_migrations/__init__.py --> abstra_internals/repositories/project/json_migrations/migration_010.py;
    abstra_internals/repositories/project/json_migrations/migration_010.py --> abstra_internals/repositories/project/json_migrations/__init__.py;
    abstra_internals/repositories/project/json_migrations/__init__.py --> abstra_internals/repositories/project/json_migrations/migration_011.py;
    abstra_internals/repositories/project/json_migrations/migration_011.py --> abstra_internals/repositories/project/json_migrations/__init__.py;
    abstra_internals/repositories/project/json_migrations/__init__.py --> abstra_internals/repositories/project/json_migrations/migration_012.py;
    abstra_internals/repositories/project/json_migrations/migration_012.py --> abstra_internals/repositories/project/json_migrations/__init__.py;
    abstra_internals/server/apps/__init__.py --> abstra_internals/server/apps/__init__.py;
    abstra_internals/utils/__init__.py --> abstra_internals/utils/__init__.py;
    abstra_internals/utils/__init__.py --> abstra_internals/utils/packages.py;
    abstra_internals/utils/packages.py --> abstra_internals/utils/__init__.py;
    abstra_internals/widgets/__init__.py --> abstra_internals/widgets/__init__.py;
    abstra_internals/widgets/__init__.py --> abstra_internals/widgets/metadata_parsed.py;
    abstra_internals/widgets/metadata_parsed.py --> abstra_internals/widgets/__init__.py;
    abstra_internals/widgets/library/CameraInput.py --> abstra_internals/widgets/library/__init__.py;
    abstra_internals/widgets/library/__init__.py --> abstra_internals/widgets/library/CameraInput.py;
    abstra_internals/widgets/library/ImageInput.py --> abstra_internals/widgets/library/__init__.py;
    abstra_internals/widgets/library/__init__.py --> abstra_internals/widgets/library/ImageInput.py;
    abstra_internals/widgets/library/VideoInput.py --> abstra_internals/widgets/library/__init__.py;
    abstra_internals/widgets/library/__init__.py --> abstra_internals/widgets/library/VideoInput.py;
