[tool.poetry]
name = "circular-imports"
version = "0.1.0"
description = ""
authors = ["Bruno Vieira Costa <bruno@abstra.app>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
