name: Publish release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  upload_pip:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: poetry install
      
      - name: Set version
        run: poetry version $TAG

      - name: Build package
        run: poetry build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}